import '@/styles/globals.css';

import SessionProvider from '@/components/SessionProvider';
import Header from '@/components/common/Header';
import { cn } from '@/utils/style';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'LawLine',
  description: 'Generated by create next app',
  icons: {
    icon: 'images/Favicon192.png',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={cn(
          'scrollbar flex overflow-x-hidden',
          'bg-slate-950 text-sm text-slate-50',
          'lg:text-base'
        )}
      >
        <SessionProvider session={session}>
          <div className="flex flex-1 flex-col">
            <Header />
            <div className="flex flex-1 flex-col overflow-y-auto">
              <main className="flex flex-1 flex-col">
                {children}
                <ToastContainer
                  position="top-center"
                  autoClose={3000}
                  closeOnClick
                  pauseOnFocusLoss={false}
                  theme="dark"
                />
              </main>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
